### ISSUE TITLE
libEM/sparx/util_sparx.cpp does not compile on CentOS6 6.7 ?

### ISSUE THREAD

**Issue by buildqa** [cryoem/eman2#2]
I see the following error when trying to build with gcc on CentOS 6.7,

libEM/sparx/util_sparx.cpp:26532: error: ‘fftwf_alloc_real’ was not declared in this scope

.... and the source file lists,

26529 #ifdef _WIN32
26530         float _cvv = (float *) malloc(2_size_sizeof(float));
26531 #else
26532         float *cvv = fftwf_alloc_real(2_size);
26533 #endif  //_WIN32
26534

There is no other instance of "fftwf_alloc_real" in this file.  I'm building with libfftw3f.so.3.3.2.  I have not built the source in a few months, but this configuration used to work.

**Comment by sludtke42** [comment]
Others have seen something similar recently. It appears to be a bad header in one of the CENTOS FFTW rpms. If you recompile and install FFTW from source this has solved the problem in at least 1 case.
----------------------------------------------------------------------------
Steven Ludtke, Ph.D.
Professor, Dept. of Biochemistry and Mol. Biol.                Those who do
Co-Director National Center For Macromolecular Imaging	           ARE
Baylor College of Medicine                                     The converse
sludtke@bcm.edu  -or-  stevel@alumni.caltech.edu               also applies
http://ncmi.bcm.edu/~stevel

**Comment by pawelpap9** [comment]
Hi


This is a valid fftw function.  I would assume recompilation of fftw library would help. 

Regards,
Pawel

**Comment by buildqa** [comment]
Hello and thanks for the follow-ups.

I saved the git log and went thru it, then after looking at

   662 commit 47bb46900e285c0989353b925f70553d70daa079
   663 Author: Pawel <pawelpap@att.net>
   664 Date:   Mon Jul 18 17:44:53 2016 -0500
   665 
   666     fftw in util
   667 
   668 commit e551f494334fae04eab758f2272d97280aec9210
   669 Merge: b675ced 0ad35c2
   670 Author: James Michael Bell <jmbell91@gmail.com>
   671 Date:   Mon Jul 18 16:22:29 2016 -0500
   672 
   673     Merge branch 'master' of github.com:cryoem/eman2
   674 

.. I checked out using hash e551f494334fae04eab758f2272d97280aec9210, and now everything builds again.  I know this does not necessarily mean that the the very next commit broke compilation, but something after that  did.

On my build system this is what I have for fftw libs,

 $ cat /etc/redhat-release
CentOS release 6.7 (Final)

 $ yum list installed | grep fftw
fftw.x86_64                            3.2.1-3.1.el6          @base             
fftw-devel.x86_64                      3.2.1-3.1.el6          @base             
fftw2.x86_64                           2.1.5-21.el6           @epel             
fftw2-devel.x86_64                     2.1.5-21.el6           @epel             

 $ yum list available | grep fftw
fftw.i686                                    3.2.1-3.1.el6               base   
fftw-devel.i686                              3.2.1-3.1.el6               base   
fftw-static.x86_64                           3.2.1-3.1.el6               base   
fftw2.i686                                   2.1.5-21.el6                epel   
fftw2-devel.i686                             2.1.5-21.el6                epel   
fftw2-static.i686                            2.1.5-21.el6                epel   
fftw2-static.x86_64                          2.1.5-21.el6                epel   
root-fftw.x86_64                             5.34.36-1.el6               epel   
 

So it looks like I have the latest shared 64 bit devel and non-revel fftw and fftw2 libs installed, but now these do not work with the source code changes after ~7/18 because of the addition of some new fftw function?   I don't see how uninstalling and re-installing the same RPM's is going to fix that.  Are you folks adding a dependency on a different versions of fftw libs?  I would be interested to know what version of these RPM's and/or the fftw libs you are building against.

Thanks again.

**Comment by pawelpap9** [comment]
Hi

Fftw2 is the previous version of the library. We are using fftw3, version 3.3.4. 

Regards,
Pawel

**Comment by pawelpap9** [comment]
Hi

Let me add one more thing. I did try to use yum and/or rocks in the past, but I found the experience frustrating. The reason was the same kind of problems you are experiencing. In short, it was difficult to figure what versions of libraries were installed and how to move around them. As soon as I switched to loading libraries directly from the developers life became easier. 

Regards,
Pawel

**Comment by shadowwalkersb** [comment]
This issue is very old. Closing.
